[workspace]
members = ["crates/app", "crates/nats-backend"]
resolver = "2"

[workspace.package]
version = "0.1.28" # x-release-please-version
edition = "2024"
rust-version = "1.92"
license = "MIT"
repository = "https://github.com/mcthesw/easy-nats"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
panic = "unwind"

