[workspace]
members = ["crates/app", "crates/nats-backend"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/mcthesw/easy-nats"

[patch.crates-io]
egui_dock = { git = "https://github.com/mcthesw/egui_dock.git", rev = "5dfa88feb4dddbc26eda0c0a5b469182816cb2ce" }
